[package]
name = "inds"
version = "0.1.0"
authors = ["Patrick Tsai <penguin@patosai.com>"]

[profile.release]
debug = true

[dependencies]
log = "0.3.6"
fern = "0.3.5"
time = "0.1.35"
glob = "0.2.11"
